### ISSUE TITLE
可以发送新弹幕嘛

### ISSUE THREAD

**Issue by Chen-Xi-g** [yanerchuang/BarrageViewDemo#1]
这个可不可以发送新的弹幕，发送完之后显示新发送的弹幕

**Comment by luayua** [comment]
> 这个可不可以发送新的弹幕，发送完之后显示新发送的弹幕

这个弹幕是循环重复的，数据数据可以重置和初始化；如果要实现发送新的弹幕并加入其中，可以查看源码添加数据到数据集即可。
